### ISSUE TITLE
api POST contact/emails do not start

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#14]
I' trying to POST data in `/api/v1/contacts/4db3d7c9-f634-44c1-afb9-a01cb26de284/emails` I receive a `socket hang up` error from nodejs. and absolute no errors from `api`

eg. 

```
{
    "contact_id": "4db3d7c9-f634-44c1-afb9-a01cb26de284",
    "type": "work",
    "address": "foo@bar.tld",
    "is_primary": true
}
```

But when I POST same url with empty body, I get:

```
api_1           | 2016-04-04 13:50:24,363 ERROR [waitress][waitress] Exception when serving /api/v1/contacts/4db3d7c9-f634-44c1-afb9-a01cb26de284/emails
api_1           | Traceback (most recent call last):
api_1           |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.9.0b0-py2.7.egg/waitress/channel.py", line 338, in service
api_1           |     task.service()
api_1           |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.9.0b0-py2.7.egg/waitress/task.py", line 169, in service
api_1           |     self.execute()
api_1           |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.9.0b0-py2.7.egg/waitress/task.py", line 392, in execute
api_1           |     app_iter = self.channel.server.application(env, start_response)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 242, in __call__
api_1           |     response = self.invoke_subrequest(request, use_tweens=True)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 217, in invoke_subrequest
api_1           |     response = handle_request(request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 46, in excview_tween
api_1           |     response = view_callable(exc, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 385, in viewresult_to_response
api_1           |     result = view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
api_1           |     response = handler(request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 163, in handle_request
api_1           |     response = view_callable(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 596, in __call__
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
api_1           |     result = view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
api_1           |     response = view(request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/cornice/service.py", line 553, in wrapper
api_1           |     validate_colander_schema(args['schema'], request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/cornice/schemas.py", line 169, in validate_colander_schema
api_1           |     qs, headers, body, path = extract_request_data(request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/cornice/util.py", line 183, in extract_request_data
api_1           |     body = deserializer(request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/caliopen/api/base/deserializer.py", line 7, in json_deserializer
api_1           |     if request.json_body:
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/request.py", line 234, in json_body
api_1           |     return json.loads(text_(self.body, self.charset))
api_1           |   File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
api_1           |     return _default_decoder.decode(s)
api_1           |   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
api_1           |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
api_1           |   File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
api_1           |     raise ValueError("No JSON object could be decoded")
api_1           | ValueError: No JSON object could be decoded
web_1           | POST /api/v1/contacts/4db3d7c9-f634-44c1-afb9-a01cb26de284/emails 500 57.595 ms - 110
```

PS: Same problem with routes like `contact/{id}/addresses` and `contact/{id}/zadazd` and `dzlkjdlakjdz`

o.O

**Comment by iamdey** [comment]
I'm digging into the problem and going down:

* I've added a simple route for GET and POST : /api/v1/echo -> it works perfectly
* I'm calling directly pyramid app (using port 6543), I've allowed CORS on each route I need to call. So I got 200 on first OPTION  call but 500 on effective POST:

```
api_1           | 2016-04-05 14:55:13,751 ERROR [waitress][waitress] Exception when serving /api/v1/contacts/69266b7d-9b36-4cc6-b3c3-85bf337b4225/emails
api_1           | Traceback (most recent call last):
api_1           |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.9.0b0-py2.7.egg/waitress/channel.py", line 338, in service
api_1           |     task.service()
api_1           |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.9.0b0-py2.7.egg/waitress/task.py", line 169, in service
api_1           |     self.execute()
api_1           |   File "/usr/local/lib/python2.7/dist-packages/waitress-0.9.0b0-py2.7.egg/waitress/task.py", line 392, in execute
api_1           |     app_iter = self.channel.server.application(env, start_response)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 242, in __call__
api_1           |     response = self.invoke_subrequest(request, use_tweens=True)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 217, in invoke_subrequest
api_1           |     response = handle_request(request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 46, in excview_tween
api_1           |     response = view_callable(exc, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 385, in viewresult_to_response
api_1           |     result = view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
api_1           |     response = handler(request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/router.py", line 163, in handle_request
api_1           |     response = view_callable(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 596, in __call__
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 245, in _secured_view
api_1           |     return view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
api_1           |     result = view(context, request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/pyramid-1.5.8-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
api_1           |     response = view(request)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/cornice/service.py", line 571, in wrapper
api_1           |     response = view_()
api_1           |   File "/srv/caliopen/src/caliopen.api.user/caliopen/api/user/contact.py", line 208, in collection_post
api_1           |     ReturnEmail)
api_1           |   File "/srv/caliopen/src/caliopen.api.user/caliopen/api/user/contact.py", line 109, in _create
api_1           |     created = getattr(contact, add_func)(params)
api_1           |   File "/srv/caliopen/src/caliopen.base.user/caliopen/base/user/core/contact.py", line 284, in add_email
api_1           |     return self._add_relation('emails', email)
api_1           |   File "/srv/caliopen/src/caliopen.base/caliopen/base/core/mixin.py", line 47, in _add_relation
api_1           |     self.save()
api_1           |   File "/srv/caliopen/src/caliopen.base/caliopen/base/core/base.py", line 76, in save
api_1           |     return self.model.save()
api_1           |   File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/models.py", line 689, in save
api_1           |     if_exists=self._if_exists).save()
api_1           |   File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/query.py", line 1357, in save
api_1           |     return self.update()
api_1           |   File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/query.py", line 1340, in update
api_1           |     self._delete_null_columns()
api_1           |   File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/query.py", line 1270, in _delete_null_columns
api_1           |     self._execute(ds)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/query.py", line 1235, in _execute
api_1           |     tmp = connection.execute(q, consistency_level=self._consistency, timeout=self._timeout)
api_1           |   File "/usr/local/lib/python2.7/dist-packages/cassandra/cqlengine/connection.py", line 173, in execute
api_1           |     result = session.execute(query, params, timeout=timeout)
api_1           |   File "cassandra/cluster.py", line 1581, in cassandra.cluster.Session.execute (cassandra/cluster.c:27107)
api_1           |     return self.execute_async(query, parameters, trace, custom_payload, timeout).result()
api_1           |   File "cassandra/cluster.py", line 3145, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:60227)
api_1           |     raise self._final_exception
api_1           | InvalidRequest: code=2200 [Invalid query] message="Unknown identifier privacy_features"
```

**Comment by iamdey** [comment]
But the good news is that the address is added using direct connection

**Comment by gdchamal** [comment]
Different problems here. Second traceback sound like your cassandra models are not up to date. Run a caliopen setup command, should fix it.

First traceback, I think that content-type header application/json is missing.

**Comment by iamdey** [comment]
you right for the first pbm:

Api works perfectly, I finally found that a middleware in expressjs app was guilty, so api was never called when application/json content type is set.

For the second pbm, I've already clean all the things and still happen. I will retry your command and maybe open a new issue.

**Comment by gdchamal** [comment]
There is some caveats in cqlengine schema synchronization process as far I experiment.
Delete of cassandra and elasticsearch data and a load-fixtures is the way to bypass this situation.

https://datastax.github.io/python-driver/api/cassandra/cqlengine/management.html#cassandra.cqlengine.management.sync_table

**Comment by iamdey** [comment]
pbm 2 solved for after a full reload of the environment 

```
cd bin
./update && ./stop
sudo rm -r ../.data
docker-compose rm
./start
./load-fixtures
```

I'll close this issue when the referenced PR on web is merged
